server:
  port: 8080

build:
  version: "@version@"

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:tgDataBase}?ApplicationName=${spring.application.name}
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 130263
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  application:
    name: "@project.name@"